In [2]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing

# importing the dataset

iris_df = pd.read_csv('Iris.csv')
iris_df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
# Identify independent variables x

x = iris_df.iloc[:,[1,2,3,4]].values
print(x)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
# Encode dependent variable y such that 'Iris-setosa' is encoded as 0, and 
# 'Iris-versioclor' and 'Iris-virginica are both encoded as 1

iris_df['Species'] = iris_df['Species'].replace({'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 1})
y = iris_df['Species']




/var/folders/m7/3y4fdpjn45qdddmm1wfk91x40000gn/T/ipykernel_18340/518024225.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  iris_df['Species'] = iris_df['Species'].replace({'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 1})


In [5]:
# Split the data into training and test set

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)



In [6]:
# Use sklearn's logistic regression function to fit a model and make predictions
# on the test set

model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)


In [7]:
# Use sklearn to generate a confusion matrix, which compares the predicted 
# labels to the actual labels (gold labels)

from sklearn.metrics import confusion_matrix

matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[11  0]
 [ 0 19]]


Analyse the confusion matrix and provide a prediction, in a comment, whether the model is likely to have higher precision, higher recall, or similar precision and recall.

From the matrix, we can see 11 true negatives, 0 false positives, 0 false negatives and 19 true positives.

-Given Precision is TP/TP + FP, we get 19/(19+0) = 1. So high precision.

-Given Recall is TP/TP + FN, we get 19/(19+0) =1. So high recall.

Level of precision and recall the same.

In [8]:
# Code:
accuracy = (matrix[0, 0] + matrix[1, 1]) / np.sum(matrix)
print("Accuracy:", accuracy)

precision = matrix[1, 1] / (matrix[0, 1] + matrix[1, 1])
print("Precision:", precision)

recall = matrix[1, 1] / (matrix[1, 0] + matrix[1, 1])
print("Recall:", recall)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
